spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show_sql: true
    properties:
      hibernate:
        format-sql: true
  mail:
    host: smtp.gmail.com
    port: 465 #587
    username: tpkdmta@gmail.com
    password: gujjhsmjknbgygoo
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
        starttls:
          enable: true
    protocol: smtp
application:
  file:
    reports-dir: reports
  security:
    jwt:
      secret-key: 36541236987412589632587412563214569874563211mySecretKeyGenerator78
      expiration: 86400000