name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_IMAGE: 'dockermintoua/sms-api'
  DOCKER_TAG: 'latest'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Java Environment
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Build Application
        run: mvn clean install

  docker:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_TAG }}
          registry: ${{ env.DOCKER_REGISTRY }}
          dockerfile: Dockerfile
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}